### ISSUE TITLE
How to open the consent popup?

### ISSUE THREAD

**Issue by merbin2012** [MrRotella/cordova-plugin-gdpr-choices#3]
There is no option to open the consent popup

**Comment by MrRotella** [comment]
The management of the privacy message via Google UMP is not the subject of this plugin, therefore it must be managed in another way.

**Comment by MrRotella** [comment]
The management of the privacy message via Google UMP is not the subject of this plugin, therefore it must be managed in another way.

**Comment by MrRotella** [comment]
The management of the privacy message via Google UMP is not the subject of this plugin, therefore it must be managed in another way.
